### PR TITLE
Feature/jdb8s cmdline plus

### PR DESCRIPTION
**Pull request by dreamcat4**
2 commits:
1. Rebased the the last PR #158 on to today's master.
2. Added a compile time flag to it, as was requested but missing from last PR.

Hope that's enough to get it accepted.
Just testing it now.

### CODE REVIEW

**Comment by dreamcat4** [comment]
OK I am testing this code. However get an impression something may be wrong with it. As trying to use it, has crashed znc.

@jdb8 Any chance you can come back and look at your code again? It seems kindda... buggy.

I do not wish discourage this particular feature or it's adoption. As executing the cmdline on a hilight is indeed a very useful feature for many diverse situations. However maybe with such behaviour it should at least be flagged EXPERIMENTAL in the README file. So the others who desperately need it can improve / work upon, push up additional fixes.

**Comment by jdb8** [comment]
Hmm, strange - I freely admit that the code was just an experiment and that
I am certainly not an experienced C++ developer. However I've used it
personally for a while and never had any crashes. Perhaps our environments
differ? Any other diagnostic information you can provide specifically?

I can take another look when I have spare time and try to clean up some of
the known bugs (one specifically relating to zombie processes - the code
isn't dealing with cleaning up well enough).

**Comment by dreamcat4** [comment]
Thanks @jdb8.

My environment: `ubuntu 16.04`
znc-push version: `v1.0.0-129-g405e541`

```
root@irssi:/# apt show znc
Package: znc
Version: 1.6.2-2build1
Priority: optional
Section: universe/net
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Patrick Matthäi <pmatthaei@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 5377 kB
Depends: libc6 (>= 2.14), libgcc1 (>= 1:3.0), libicu55 (>= 55.1-1~), libsasl2-2, libssl1.0.0 (>= 1.0.1), libstdc++6 (>= 5.2), zlib1g (>= 1:1.1.4)
Recommends: znc-tcl, znc-perl, znc-python
Conflicts: znc-extra, znc-webadmin
Breaks: znc-extra (<< 1.6.2-2build1)
Replaces: znc-extra, znc-webadmin
Homepage: http://znc.sourceforge.net/
Download-Size: 1373 kB
APT-Manual-Installed: yes
APT-Sources: http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
Description: advanced modular IRC bouncer
```

My znc is an official APT release binaries, so unforunately was not compiled with the necessary debugging support flag for gdb etc.

**Comment by jdb8** [comment]
@dreamcat4 hey, just taking another look at this now. Unfortunately without any kind of stacktrace I'm not able to be of much help. Is it possible to compile a separate version of znc on your system with gdb support in order to provide this information?

I'm actually surprised that znc itself doesn't log debug information on crash anywhere - perhaps there is a log file floating around?

**Comment by dgw** [comment]
Ping for rebase and/or any further info on progress debugging the aforementioned crash issue.

**Comment by dgw** [comment]
Closing as stale — over 3 years since last activity.

**Pull request closed without merging**
